name: Gasket Build

on:
    workflow_dispatch:
    push:
      branches: [ "build" ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps: 
            - name: Install Build Tools
              run: sudo apt install git devscripts dkms debhelper coreutils
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                path: 'build'
            - name: Build
              run: | 
                cd build
                debuild -us -uc -tc -b
            - name: Artifact SHA256 Print
              run: |
                ls -lA
                sha256sum gasket-dkms*
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: gasket-dkms
                path: gasket-dkms*

            